"""Generate the paper's LaTeX tables and copy its figures into paper/.

Reads results/tables/*.csv (from make_tables.py) and results/figures/*.pdf (from make_figures.py).
Writes paper/tables/*.tex and paper/figures/*.pdf, so the paper/ folder can be uploaded to Overleaf as is.

Usage (from the project root):
    python scripts/build_paper_assets.py
"""

import shutil
from pathlib import Path

import pandas as pd

TABLES_IN = Path("results/tables")
FIGURES_IN = Path("results/figures")
PAPER = Path("paper")


def tex(value) -> str:
    """Escape the characters that appear in our result tables."""
    return str(value).replace("%", r"\%").replace("&", r"\&").replace("_", r"\_")


def table_env(label: str, caption: str, colspec: str, header: list[str], rows: list[list[str]],
              fit_width: bool = False) -> str:
    body = [r"\toprule", " & ".join(header) + r" \\", r"\midrule"]
    body += [" & ".join(tex(v) for v in row) + r" \\" for row in rows]
    body.append(r"\bottomrule")
    tabular = "\\begin{tabular}{" + colspec + "}\n" + "\n".join(body) + "\n\\end{tabular}"
    if fit_width:
        tabular = "\\resizebox{\\textwidth}{!}{%\n" + tabular + "}"
    # IJPHM layout: tables span both columns (table*) and the caption goes below the table.
    return (f"% Generated by scripts/build_paper_assets.py -- do not edit by hand.\n"
            f"\\begin{{table*}}[t]\n\\centering\n\\small\n{tabular}\n"
            f"\\caption{{{caption}}}\n\\label{{{label}}}\n\\end{{table*}}\n")


def table1() -> str:
    df = pd.read_csv(TABLES_IN / "table1_main.csv", dtype=str)
    metrics = [c for c in df.columns if c != "Model"]
    names = {"Conformal coverage (nominal 0.90)": "Conformal coverage (nominal 0.90)",
             "Best possible automation at 5%": "Best possible automation at 5% target"}
    rows = [[names.get(m, m)] + list(df[m]) for m in metrics]
    caption = ("Main results (temperature scaling). Random Forest, SVM and XGBoost use the fault-frequency features; "
               "the 1D-CNN uses the raw vibration signal. In-domain: leave one source bearing out, raw probabilities. "
               "Real damage: mean [95\\,\\% interval] from 2,000 bootstrap draws over calibration rotations and "
               "test bearings.")
    header = ["Metric"] + [r"\textbf{" + m + "}" for m in df["Model"]]
    return table_env("tab:main", caption, "l" + "c" * len(df), header, rows)


def table2() -> str:
    df = pd.read_csv(TABLES_IN / "table2_feature_ablation.csv", dtype=str)
    header = [r"\makecell[l]{Features}", "Model", r"\makecell{In-domain\\accuracy}", r"\makecell{In-domain\\ECE}",
              r"\makecell{Real\\accuracy}", r"\makecell{Real\\ECE}", r"\makecell{Error at\\5\% target}",
              r"\makecell{Runs exceeding\\5\% target}", r"\makecell{Conformal\\coverage}"]
    caption = ("Feature ablation: all nine features vs fault-frequency features only. Means over 105 calibration "
               "rotations; temperature scaling; marginal split conformal prediction, nominal coverage 0.90.")
    return table_env("tab:ablation", caption, "llccccccc", header, df.values.tolist(), fit_width=True)


def table3() -> str:
    df = pd.read_csv(TABLES_IN / "table3_real_calibration.csv", dtype=str)
    header = ["Model", "Calibrated on", r"\makecell{Error at\\5\% target}", r"\makecell{Draws meeting\\5\% target}",
              "Automated", "ECE", r"\makecell{Conformal\\coverage}"]
    caption = ("Calibrating on artificial bearings vs one or two labelled real bearings per class (fault-frequency "
               "features, temperature scaling). Mean [2.5th, 97.5th percentile] over 50 draws per setting; "
               "artificial-bearing values pooled over all 100 draws. Within each draw, all settings are scored on "
               "the same test bearings. Draws meeting the target counts only draws that automated at least one case.")
    return table_env("tab:realcal", caption, "llccccc", header, df.values.tolist(), fit_width=True)


def table4() -> str:
    df = pd.read_csv(TABLES_IN / "table4_conditions.csv", dtype=str)
    header = ["Condition", "Model", r"\makecell{In-domain\\accuracy}", r"\makecell{Real\\accuracy}",
              r"\makecell{Error at\\5\% target}", r"\makecell{Runs exceeding\\5\% target}",
              r"\makecell{Conformal\\coverage}", r"\makecell{Missed faults\\(share of errors)}"]
    caption = ("All four Paderborn operating conditions (shaft speed, load torque, radial force), with the same bearing "
               "splits. Fault-frequency features, temperature scaling. Real damage: mean [95\\,\\% interval] from 2,000 "
               "bootstrap draws. Missed faults: share of real-damage errors that call a damaged bearing healthy.")
    return table_env("tab:conditions", caption, "llcccccc", header, df.values.tolist(), fit_width=True)


def main() -> None:
    (PAPER / "tables").mkdir(parents=True, exist_ok=True)
    (PAPER / "figures").mkdir(parents=True, exist_ok=True)
    for name, build in (("table1_main", table1), ("table2_feature_ablation", table2),
                        ("table3_real_calibration", table3), ("table4_conditions", table4)):
        (PAPER / "tables" / f"{name}.tex").write_text(build())
    for pdf in sorted(FIGURES_IN.glob("*.pdf")):
        shutil.copy2(pdf, PAPER / "figures" / pdf.name)
    print("Wrote paper/tables/*.tex and copied", len(list(FIGURES_IN.glob("*.pdf"))), "figures")


if __name__ == "__main__":
    main()
